// Copyright 2022 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Use the <code>chrome.pdfViewerPrivate</code> API for specific browser
// functionality that the PDF Viewer needs from outside the PDF plugin. This API
// is exclusively for the PDF Viewer.
namespace pdfViewerPrivate {
  // Must match `SaveRequestType` in `pdf/mojom/pdf.mojom` and
  // `tools/typescript/definitions/pdf_viewer_private.d.ts`.
  enum SaveRequestType {
    ANNOTATION,
    ORIGINAL,
    EDITED,
    SEARCHIFIED
  };

};
