/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "c26a7bc8b8069f0f77ba3e4fb042e18116456ede-"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
