/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "d95a5d65bf67995a01ff714601e286252a53a0b1"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
