/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "fda8139b467c26d85af7de898afb57dca20d80ca-"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
