/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "56ca847e9ea70a5c56fa3d634361da1002fb284b"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
