/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "d5190fedde334f4c1c3e3851e62966304d236bae"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
