/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "cc99454a94d72bc0ae0a87712cf0c6a106e03903"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
