/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_WEBGPU_DAWN_COMMIT_HASH_H_
#define GPU_WEBGPU_DAWN_COMMIT_HASH_H_

#define DAWN_COMMIT_HASH "a94afcc3f32ac522df1383bb80b78680c7b1de70"

#endif  // GPU_WEBGPU_DAWN_COMMIT_HASH_H_
